# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  FOD_API_BASE: 'https://api.ams.fortify.com'   # AMS; use emea/apac base if needed
  FOD_RELEASE_ID: '945671'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: 'WebGoat'
    FodConnection: 'AMS_pjtest'
    ReleaseOptions: '0'
    ReleaseId: 945671
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'none'
    PollingInterval: 2
    PolicyFailAction: '0'

- powershell: |
    $ErrorActionPreference = 'Stop'
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $base   = "$(FOD_API_BASE)"
    $relId  = "$(FOD_RELEASE_ID)"
    $cid    = "$(FOD_CLIENT_ID)"
    $csec   = "$(FOD_CLIENT_SECRET)"

    # How long to wait (in minutes) before giving up
    $maxWaitMinutes = 15
    # How often to poll (in seconds)
    $pollSeconds = 60

    Write-Host "Requesting OAuth token..."
    $tokenResp = Invoke-RestMethod -Method Post -Uri "$base/oauth/token" `
      -ContentType 'application/x-www-form-urlencoded' `
      -Body @{
        grant_type='client_credentials'
        scope='api-tenant'
        client_id=$cid
        client_secret=$csec
      }
    $tok = $tokenResp.access_token
    if (-not $tok) { throw "No access_token returned from FoD." }

    $elapsed = 0
    $latest = $null

    while ($elapsed -lt ($maxWaitMinutes*60)) {
      Write-Host "Polling scans for release $relId (elapsed ${elapsed}s)..."
      $scans = Invoke-RestMethod -Method Get -Uri "$base/api/v3/releases/$relId/scans?limit=50" `
        -Headers @{ Authorization = "Bearer $tok" }

      if ($scans.items) {
        $latest = $scans.items |
          Where-Object { $_.scanType -eq 'Static' -and $_.analysisStatusType -eq 'Completed' } |
          Sort-Object -Property completedDateTime -Descending |
          Select-Object -First 1
      }

      if ($latest) {
        Write-Host "Found completed static scan: scanId=$($latest.scanId)"
        break
      }

      Write-Host "No completed static scan yet, sleeping $pollSeconds seconds..."
      Start-Sleep -Seconds $pollSeconds
      $elapsed += $pollSeconds
    }

    if (-not $latest) {
      throw "Timed out after $maxWaitMinutes minutes waiting for a completed static scan on release $relId."
    }

    $scanId = $latest.scanId
    $outDir = "$(Build.ArtifactStagingDirectory)\FoD"
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
    $outFile = Join-Path $outDir ("scan-$scanId.fpr")

    Write-Host "Downloading FPR for scanId=$scanId..."
    Invoke-WebRequest -Method Get -Uri "$base/api/v3/scans/$scanId/fpr" `
      -Headers @{ Authorization = "Bearer $tok" } -OutFile $outFile

    Write-Host "FPR saved to $outFile"
  displayName: "Download most recent completed FoD FPR (with wait/retry)"
  env:
    FOD_CLIENT_ID: $(FOD_CLIENT_ID)         # mark as secret in pipeline UI
    FOD_CLIENT_SECRET: $(FOD_CLIENT_SECRET) # mark as secret in pipeline UI


- task: PublishBuildArtifacts@1
  displayName: "Publish FoD FPR artifact"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\FoD'
    ArtifactName: 'fod-fpr'
    publishLocation: 'Container'

